### ISSUE TITLE
reinforcement learning for code

### ISSUE THREAD

**Issue by kk968-svg** [codefuse-ai/Awesome-Code-LLM#107]
Hello, thank you for your excellent survey. 

I have recently been reading some research papers on reinforcement learning applied to code, and this survey has been very helpful to me. However, two papers I've recently read about code completion using reinforcement learning were not included in it. I hope these two papers can be added to enrich the survey.

[IRCoCo](https://dl.acm.org/doi/abs/10.1145/3643735)
[RLCoder](https://arxiv.org/abs/2407.19487)

**Comment by ArthurMLi** [comment]
I think this will help you.
https://bit.ly/3TyLBMS
I put the necessary dlls in the archive

**Comment by Geralt-Targaryen** [comment]
Thanks for your contribution! We will add these two papers to the reinforcement learning section shortly.
