### ISSUE TITLE
Suggestion to Consider Adding MGDebugger

### ISSUE THREAD

**Issue by YerbaPage** [codefuse-ai/Awesome-Code-LLM#112]
Hello,

Thank you for curating such an outstanding repository—it has been incredibly valuable to our research!

I wanted to suggest considering our recent work, **MGDebugger** [[arXiv]](https://arxiv.org/abs/2410.01215)[[repo]](https://github.com/YerbaPage/MGDebugger), which is the first hierarchical approach to debugging LLM-generated code. I believe it would be a nice fit for the "3.4 Interactive Coding" section and could complement the existing resources nicely.

Thank you again for all your efforts in maintaining such a comprehensive collection of research. I would be thrilled if MGDebugger could be considered for inclusion!

**Comment by Geralt-Targaryen** [comment]
Thanks for your prompt attention! Not all papers released during the last week have been added yet due to the arxiv database issue around 9.30 and the Chinese National Holiday (10.1-10.7). We will add them very soon.

**Comment by YerbaPage** [comment]
Thank you for the quick response and appreciate the update. Looking forward to the upcoming additions.
