### ISSUE TITLE
Suggestion to Consider Adding CoEdPilot

### ISSUE THREAD

**Issue by AWGiaGia** [codefuse-ai/Awesome-Code-LLM#119]
Thank you for building such an excellent code repository; it has been a great help to me.

I wanted to suggest considering a recent work published by Cophi group in SJTU, CoEdPilot [[arxiv]](https://arxiv.org/abs/2408.01733) [[repo]](https://github.com/code-philia/CoEdPilot), which enhances the model's locating and code-editing capabilities by indexing previous edits and context edits. I think it would be nice fit for the "5.8 Repository-Level Coding" section and could make a small contribution to the community.

Thank you again for your efforts in improving the community; such a repository is truly invaluable.

**Comment by Geralt-Targaryen** [comment]
Thanks for your recognition of our work! We will certainly add it in the next update.
