### ISSUE TITLE
GALLa: Graph Aligned Large Language Models for Improved Source Code Understanding

### ISSUE THREAD

**Issue by SuperCB** [codefuse-ai/Awesome-Code-LLM#126]
When wiil you release the source code and ckpt of this paper?
 [link](https://arxiv.org/abs/2409.04183)

**Comment by Geralt-Targaryen** [comment]
Yes. Due to logistical reasons, the source code of this paper will be released in another repo under codefuse-ai after the paper has been accepted for publication.

**Comment by SuperCB** [comment]
Thanks
