### ISSUE TITLE
A new proactive alignment approach for more secure code model 

### ISSUE THREAD

**Issue by XZ-X** [codefuse-ai/Awesome-Code-LLM#134]
Hi,

Nice work! I appreciate your efforts on this survey. It gives me clearer picture for the roadmap in the code llm domain.

I found the current list does not contain alignment stage methods for code model security yet.
Our team recently makes some progress on code model security alignment. We propose a proactive method that elicits insecure code from a code model and applies fixes to it. Here's our [preprint](https://arxiv.org/abs/2411.12882).
Hope our work can contribute a bit to the survey :)

Cheers,
Xiangzhe

**Comment by Geralt-Targaryen** [comment]
Thanks for sharing your work with us! We will add it in the next update.
