### ISSUE TITLE
Paper: LLMs as Continuous Learners : Improving the Reproduction of Defective Code in Software Issues

### ISSUE THREAD

**Issue by yingweima2022** [codefuse-ai/Awesome-Code-LLM#136]
Thank you for your great work on this survey! It provides a clear and comprehensive roadmap in the code LLM domain.

Our team has recently made some progress on code agent and issue reproduction. We propose a method called EvoCoder, a multi-agent continuous learning framework that focuses on improving the reproduction of defective code in software issues. This aligns with the broader goals discussed in your survey.

Title: LLMs as Continuous Learners: Improving the Reproduction of Defective Code in Software Issues

Preprint: [arXiv:2411.13941](https://arxiv.org/pdf/2411.13941)

**Comment by Geralt-Targaryen** [comment]
Thanks for sharing your work! We have added it in [section 3.3](https://github.com/codefuse-ai/Awesome-Code-LLM?tab=readme-ov-file#33-code-agents).
