### ISSUE TITLE
Interactive Coding Tasks

### ISSUE THREAD

**Issue by john-b-yang** [codefuse-ai/Awesome-Code-LLM#2]
Hello, thanks for the great survey paper!

I was thinking you might find my recently accepted work on InterCode, a benchmark for constructing interactive coding tasks towards LM evaluation, would be relevant to the Code Evaluation -> Text to Code section of your work.

* [Website](https://intercode-benchmark.github.io/)
* [Paper](https://arxiv.org/abs/2306.14898)

**Comment by ss41979310** [comment]
Hello John, sure! Congratulations on your work!

**Comment by john-b-yang** [comment]
Sweet, thanks so much @ss41979310!
