### ISSUE TITLE
企业合作及访问交流

### ISSUE THREAD

**Issue by qianshuang** [codefuse-ai/Awesome-Code-LLM#39]
您好，我们公司试用了贵公司的CodeFuse大模型，效果不错，希望能有更进一步的合作，期待能进行一次访问交流。
期待能收到进一步的反馈及联系方式。

**Comment by Geralt-Targaryen** [comment]
非常荣幸我们的产品能给您带来良好体验。您可在我们的[主页](https://codefuse.alipay.com/welcome/product)底部扫码加入交流微信群。
