### ISSUE TITLE
Willing to include amplified.dev?

### ISSUE THREAD

**Issue by TyDunn** [codefuse-ai/Awesome-Code-LLM#54]
We have been working with platform development teams (similar to the one described at Ant Group behind this repo) to write [amplified.dev](https://amplified.dev). It's a living document that begins to sketch a vision for a future where developers are amplified, not automated. 

I noticed most of the resources listed here are academic papers, but I was wondering if you would be willing to list `amplified.dev` under the `User-LLM Interaction` or somewhere else in this repo. If yes, then I would open a pull request to make these changes.

Thank you for your consideration!

P.S. I added a mention of this repo in [Awesome-DevAI](https://github.com/continuedev/Awesome-DevAI) today

**Comment by Geralt-Targaryen** [comment]
Sure! We always welcome contributions to our repo from the community!

**Comment by TyDunn** [comment]
Awesome. Just opened a pull request. Thank you for creating and maintaining this **awesome** repo!
