### ISSUE TITLE
Incorrect value for phi-1

### ISSUE THREAD

**Issue by rokset3** [codefuse-ai/Awesome-Code-LLM#6]
![image](https://github.com/codefuse-ai/Awesome-Code-LLM/assets/106373322/59074aac-8fef-4663-8d97-0ffab69c9eef)
phi-1 is finetuned version of phi-1-base on CodeExercises dataset, phi-1-base pretrained is 29% on HumanEval
https://arxiv.org/pdf/2306.11644.pdf

Could you please take a look on Table 4. from your paper https://arxiv.org/pdf/2311.07989.pdf.
In my humble opinion, phi-1 should be reported as an instruction-tuned model, and phi-1-base results should be reported separately

**Comment by ss41979310** [comment]
@rokset3 You are right! Great thanks! We will correct this in our next update of paper.

**Comment by rokset3** [comment]
Thanks!
P.S. The same applies with StarCoder models (they have StarCoderBase model as non SFT model)

**Comment by rokset3** [comment]
@ss41979310 I am wrong actually. After double checking the papers, Phi-1 has not been instruction tuned. It was finetuned on some more code data T_T.
